version: 2.1
jobs:
  build:
    docker:
      - image: saadqamar/circleci_devsecops_image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm test
  
  docker:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t saadqamar/circleci_devsecops_image .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push saadqamar/circleci_devsecops_image

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - docker:
          requires:
            - build
